import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/components/context/UserContext";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/Navbar";



const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Elit Tasks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`min-h-screen flex flex-col ${geistMono.variable} font-mono antialiased bg-[#0a0a0a]`}
      >
        <UserProvider>
          <Navbar />
          <main className="flex-grow bg-[#0a0a0a]">{children}</main>
        </UserProvider>
        <Footer />
      </body>
    </html>
  );
}

